kind: pipeline
name: bundle

steps:
- name: build
  image: node:lts-slim
  commands:
  - npm install
  - npx gulp bundle
  paths:
    - build/ui-bundle.zip
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
      - build/ui-bundle.zip
   checksum:
      - md5
      - sha1
  when:
    branch:
    - master
