= Antora arc42 UI
:url-opendevise: https://opendevise.com
:url-anoff: https://anoff.io
:url-default-ui: https://gitlab.com/antora/antora-ui-default

image::https://cloud.drone.io/api/badges/anoff/antora-arc42-ui/status.svg[[Build Status, link=https://cloud.drone.io/anoff/antora-arc42-ui]

This is a modified version of the original {url-default-ui}[Antora Default UI bundle]

== Use the UI bundle

[source,yaml,subs=attributes+]
----
ui:
  bundle:
    url: tbd
    snapshot: true
----

== Usage

=== Install required dependencies

 $ npm install
 $ npm install -g gulp-cli


=== Preview the UI

To build the UI and preview it in a local web server, run the `preview` command:

 $ gulp preview

=== Package for Use with Antora

If you need to bundle the UI in order to preview the UI on the real site in local development, run the following command:

  $ gulp bundle

The UI bundle will be available at [.path]_build/ui-bundle.zip_.
You can then point Antora at this bundle using the `--ui-bundle-url` command-line option.

== Copyright and License

Based on the work of OpenDevise Inc. and the Antora Project Copyright (C) 2017-2018.

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.

== Authors

* Development of Antora is led and sponsored by {url-opendevise}[OpenDevise Inc]
* {url-anoff}[Andreas Offenhaeuser]
